/* Dati: 24 apgalvojumi un 14 kandidātu sarakstu nostājas. Izvilkts no v2 HTML bez izmaiņām. */
(function(){
const DIMS = ["Ekonomika un labklājība","Drošība un ārpolitika","Vērtības, izglītība un pārvaldība"];
const DIMS_SHORT = ["Ekonomika","Drošība","Vērtības"];

const QUESTIONS = [
  /* A – ekonomika */
  {d:0, topic:"Nodokļi", text:"Nodokļu likmes tuvākajos gados nevajag samazināt – svarīgāk ir noturēt budžeta ieņēmumus.", note:"Nodokļu samazinājumus dažādā apjomā sola vairākums sarakstu."},
  {d:0, topic:"Mājokļa nodoklis", text:"Nekustamā īpašuma nodoklis vienīgajam mājoklim jāatceļ.", note:""},
  {d:0, topic:"Budžets", text:"Valsts budžetam sasaukuma laikā jākļūst bezdeficīta, un jauni solījumi jāatliek, kamēr tiem nav finansiāla seguma.", note:"Tikai daļa programmu vispār runā par deficītu un aizņēmumiem."},
  {d:0, topic:"Lielie projekti", text:"Lielie infrastruktūras projekti – Rail Baltica, jauni ceļi, publiskās un privātās partnerības būves – jāturpina un jāfinansē, arī aizņemoties.", note:""},
  {d:0, topic:"Pensijas", text:"Pensijas, īpaši minimālās, būtiski jāpaaugstina un jāindeksē biežāk.", note:""},
  {d:0, topic:"Ģimenes pabalsti", text:"Valstij nevajadzētu ieviest jaunus lielus pabalstus par bērnu piedzimšanu un audzināšanu – esošais atbalsta līmenis ir pietiekams.", note:""},
  {d:0, topic:"Veselība", text:"Veselības aprūpei jānovirza būtiski vairāk valsts līdzekļu – ap 6 % no IKP.", note:""},
  {d:0, topic:"Reģioni", text:"Lielāka nodokļu ieņēmumu daļa jāatstāj pašvaldībām, un valstij mērķtiecīgi jāatbalsta uzņēmējdarbība un mājokļi ārpus Rīgas.", note:""},
  /* B – drošība */
  {d:1, topic:"Aizsardzības dienests", text:"Obligātais valsts aizsardzības dienests jāsaglabā un jāpaplašina.", note:""},
  {d:1, topic:"Krievija un Baltkrievija", text:"Latvijai jāatjauno ekonomiskā sadarbība ar Krieviju un Baltkrieviju tur, kur tas ir izdevīgi, un jāpārskata sankcijas.", note:""},
  {d:1, topic:"Ukraina", text:"Latvijai jāturpina pilna mēroga militārs, politisks un finansiāls atbalsts Ukrainai.", note:""},
  {d:1, topic:"Aizsardzības industrija", text:"Aizsardzības naudai jāpaliek Latvijas ekonomikā – prioritāte vietējai militārajai industrijai, dronu ražošanai un pretgaisa aizsardzībai.", note:""},
  {d:1, topic:"Suverenitāte un ES", text:"Latvijai vairāk jāsargā sava suverenitāte pret pārnacionālu institūciju lēmumiem, nevis jāiet uz dziļāku integrāciju Eiropas Savienībā.", note:""},
  {d:1, topic:"Migrācija", text:"Darbaspēka imigrācija no trešajām valstīm jāierobežo stingri, arī ja uzņēmējiem trūkst darbinieku.", note:"Šo tēmu programmās skaidri izceļ tikai daži saraksti."},
  {d:1, topic:"Iekšējā drošība", text:"Policistu, ugunsdzēsēju un robežsargu algas būtiski jāceļ – iekšējā drošība ir tikpat svarīga kā militārā.", note:""},
  {d:1, topic:"Neitralitāte", text:"Latvijai jāizvairās no iesaistīšanās citu valstu militārajos konfliktos un jāturas tuvāk neitralitātei.", note:""},
  /* C – vērtības, izglītība, pārvaldība */
  {d:2, topic:"Skola 2030", text:"Reforma “Skola 2030” jāatceļ un mācību saturs jāveido no jauna.", note:""},
  {d:2, topic:"Mācību valoda", text:"Skolās jāatjauno iespēja mācīties mazākumtautību valodās vai apgūt krievu valodu kā izvēles priekšmetu.", note:""},
  {d:2, topic:"Mājasdarbi un eksāmeni", text:"Mājasdarbi un centralizētie eksāmeni jāsaglabā – bez tiem izglītības kvalitāte kritīsies.", note:""},
  {d:2, topic:"Valsts prezidents", text:"Valsts prezidents arī turpmāk jāievēl Saeimai, nevis tautai, un referendumu kārtība jāatstāj kā līdz šim.", note:""},
  {d:2, topic:"Valsts pārvalde", text:"Valsts pārvaldi nevajag krasi samazināt – ierēdņu skaita griešana pasliktinās pakalpojumus.", note:""},
  {d:2, topic:"Zinātne", text:"Zinātnei un pētniecībai jānovirza 2–3 % no IKP un jāatbalsta tās komercializācija.", note:""},
  {d:2, topic:"Augstākā izglītība", text:"Studijas valsts augstskolās jāpadara pieejamākas – vairāk budžeta vietu un lielākas stipendijas.", note:""},
  {d:2, topic:"Lauku skolas", text:"Mazās lauku skolas jāsaglabā, pat ja tajās ir maz skolēnu.", note:""}
];

/* pos: nostāja katrā no 24 jautājumiem (-2 … 2; 0 = programmā nav skaidras pozīcijas, netiek skaitīts) */
const PARTIES = [
  {nr:1, name:"Suverēnā vara / Apvienība Jaunlatvieši",
   pos:[-2,2,0,-2,2,-2,2,2, -2,0,-2,-1,2,1,1,2, 2,2,-1,-2,-2,1,1,2],
   why:{
        0:"ieviest vismaz 5 gadu moratoriju nodokļu paaugstināšanai un jaunu nodokļu ieviešanai",
        1:"atcelt nekustamā īpašuma nodokli visiem mājokļiem",
        3:"pārtraukt Rail Baltica finansēšanu, iesaldēt būvniecību un noskaidrot atbildīgās personas par līdzekļu izšķērdēšanu",
        4:"minimālās pensijas apmēru noteikt pusi no minimālās algas",
        5:"noteikt, ka ģimenes valsts pabalsts par katru bērnu ir 1/4 no minimālās algas",
        6:"nodrošināt stabilu un prognozējamu finansējumu medicīnai, prioritāri novirzot līdzekļus personāla atalgojuma celšanai",
        7:"atjaunot pašvaldībām IIN proporciju 95% apmērā, lemt par UIN pārdali par labu pašvaldībām",
        8:"atcelt jauniešu obligāto iesaukšanu Valsts aizsardzības dienestā",
        10:"nepieļaut Latvijas iesaistīšanos militārajos konfliktos, tai skaitā to finansēšanu",
        11:"pārdalīt aizsardzības budžetu iekšējās drošības garantēšanai un infrastruktūrai",
        12:"izskaust pakļāvīgu ārpolitiku, aktīvi aizstāvot Latvijas iedzīvotāju intereses",
        13:"nepieļaut augstskolu un izglītības sistēmas izmantošanu lētā darbaspēka ieviešanai valstī",
        14:"nodrošinot papildu finansējumu medicīnai un glābšanas dienestiem",
        15:"nepieļaut Latvijas iesaistīšanos militārajos konfliktos, tai skaitā to finansēšanu; sekmēt konfliktu atrisināšanu diplomātiskajā ceļā",
        16:"atcelt Skola2030 un citas skolu reformas, nodrošināt pilnvērtīgus mācību materiālus",
        17:"atjaunot skolās krievu valodas apguvi izvēles kārtībā",
        18:"ļaut skolēniem labot vismaz vienu pārbaudes darba atzīmi katrā priekšmetā ik semestri",
        19:"samazināt nepieciešamo balsu skaitu referendumu rīkošanai līdz 5% no iepriekšējās Saeimas vēlēšanās nobalsojušo skaita",
        20:"veikt valsts pārvaldes funkcionālo auditu, pārskatot iestāžu funkcijas un apvienojot atsevišķas ministrijas, samazināt ierēdņu skaitu",
        21:"ieviest mērķtiecīgu politiku zinātniski ietilpīgu uzņēmumu skaita palielināšanai un to globālās konkurētspējas stiprināšanai",
        22:"Stipendijas līdz Baltijas valstu līmenim",
        23:"nosargāt mazās lauku skolas, apvienojot administratīvo aparātu un mācībspēku bāzi"
   },
   points:["PVN 5 % pārtikai, ēdināšanai, zālēm, elektrībai un kurināmajam","Vismaz 5 gadu moratorijs nodokļu celšanai; NĪN atcelšana visiem mājokļiem","Jaunieši līdz 25 gadiem atbrīvoti no IIN","Pārtraukt airBaltic un Rail Baltica finansēšanu","Tautas vēlēts prezidents, Saeima ar 50 deputātiem, atcelts obligātais VAD iesaukums"]},

  {nr:2, name:"Mēs mainām noteikumus",
   pos:[-2,2,2,-1,0,1,0,2, 0,0,1,0,2,2,0,-1, 1,0,-2,-2,-2,0,0,1],
   why:{
        0:"Iedzīvotāju ienākuma nodoklis — visiem viena likme, pārtraucot sodīt darba ražīgumu un algas pieaugumu",
        1:"Mājokļa aizsardzība — atcelsim NĪN vienīgajam mājoklim",
        2:"Bezdeficīta budžets — jāsasniedz viena Saeimas sasaukuma laikā",
        3:"Pareizas prioritātes — Latvijas savienotība, vietējais dzelzceļš un kvalitatīvi autoceļi ir svarīgāki par Rail Baltica",
        5:"Valsts nevar nopirkt bērnus ar pabalstiem — dzimstība ir morāles un kultūras veselības izpausme",
        7:"Dzīvība reģionos — veicināsim uzņēmējdarbību reģionos, 20% no uzņēmuma nomaksātā UIN novirzot pašvaldībai",
        10:"Sabiedroto kodols — īpaši stiprināsim divpusējas attiecības ar tuvākajiem sabiedrotajiem: ASV, Baltiju, Somiju, Poliju, Ukrainu, Lielbritāniju",
        12:"pārnacionālas institūcijas nedrīkst diktēt lokālos noteikumus",
        13:"Imigrācija — totāla trešo valstu imigrācijas ierobežošana, uzturēšanās atļauju izsniegšana uz noteiktu laiku tikai Latvijā nepieejamiem kvalificētiem speciālistiem",
        15:"Sabiedroto kodols — īpaši stiprināsim divpusējas attiecības ar tuvākajiem sabiedrotajiem: ASV, Baltiju, Somiju, Poliju, Ukrainu, Lielbritāniju",
        16:"Vara skolām — pārcelsim lēmumu pieņemšanu no ministrijas uz skolām",
        18:"Eksāmenu reforma — atcelsim dārgos centralizētos eksāmenus",
        19:"Atgriezīsim reālu iespēju tautai izlemt valstiski svarīgus jautājumus, pazeminot slieksni referenduma ierosināšanai līdz 25 000 parakstu",
        20:"Ierēdņu statuss — atcelsim Valsts civildienesta likumu",
        23:"novirzot naudu skolotāju algām, mazajām skolām un skolu autonomijai"
   },
   points:["Pārnesamās balss (Īrijas) vēlēšanu sistēma; atcelta 5 % barjera","Bezdeficīta budžets viena sasaukuma laikā; ministriju un valsts uzņēmumu skaita samazināšana","10 % mikrouzņēmuma nodoklis, viena IIN likme, NĪN atcelšana vienīgajam mājoklim","Pilnīga trešo valstu imigrācijas ierobežošana","Skolu autonomija; atcelt centralizētos eksāmenus"]},

  {nr:3, name:"Saskaņas Centrs",
   pos:[2,0,0,2,2,-2,1,2, 1,1,1,0,1,0,2,-1, 0,2,0,-2,1,0,2,0],
   why:{
        0:"Ieviesīsim luksusa un neizmantotā nekustamā īpašuma nodokli",
        3:"Virzīsim Liepāja-Rīga šosejas pārbūvi par 4 joslu šoseju",
        4:"Noteiksim minimālo pensiju un garantēto sociālo minimumu virs nabadzības riska sliekšņa",
        5:"Palielināsim invaliditātes pabalstus par 25 % un bērna piedzimšanas pabalstu līdz 1000 €",
        6:"Samazināsim PVN būtiskākajām zālēm līdz 5 % un ieviesīsim stingrāku kontroli pār zāļu cenu veidošanos",
        7:"Pārcelsim daļu valsts pārvaldes darbavietu uz reģioniem",
        8:"Paredzēsim daļai VAD dalībnieku iespēju dienestu pildīt pašvaldības policijā vai civilās aizsardzības struktūrās",
        9:"godīgu starptautisko tirdzniecību labklājībai un dialogam, nepieļaujot agresijas finansēšanu",
        10:"nosodot Krievijas agresiju pret Ukrainu",
        12:"dalībvalstu konsensu, nevis lēmumu nodošanu virsnacionālam vairākumam",
        14:"Nodrošināsim prioritāru finansējumu policijas, VUGD un robežsardzes atalgojumam, aprīkojumam un darba apstākļiem",
        15:"NATO ietvarā un Eiropas spējas kopīgos iepirkumos, munīcijā, dronos, pretgaisa aizsardzībā un kiberdrošībā",
        17:"Izvirzīsim Mazākumtautību izglītības iestāžu likumu, nodrošinot izglītību mazākumtautību valodās, garantējot pilnvērtīgu valsts valodas apguvi",
        19:"Rosināsim tiešas, vispārējās Valsts Prezidenta vēlēšanas",
        20:"Veiksim valsts pārvaldes funkciju un iepirkumu auditu, samazinot birokrātiju un novirzot ietaupījumus veselībai, izglītībai, drošībai un sociālajai aizsardzībai",
        22:"Palielināsim budžeta vietu skaitu valsts augstskolās, īpaši sabiedrībai nepieciešamās nozarēs"
   },
   points:["Minimālā pensija un sociālais minimums virs nabadzības riska sliekšņa; biežāka indeksācija","Nodokļu slogs no zemajiem uz lielajiem ienākumiem; bagātības nodoklis; Valsts attīstības banka","Piedzimšanas pabalsts 1000 eiro; otrā bērna pabalsts pieckārt; bezmaksas ēdināšana līdz 9. klasei","Mažoritārā vēlēšanu sistēma, tautas vēlēts prezidents, deputātu atsaukšana","Izglītība mazākumtautību valodās; bezmaksas augstākā izglītība valsts augstskolās"]},

  {nr:4, name:"Zaļo un Zemnieku savienība",
   pos:[-1,2,0,1,1,-2,2,2, 0,0,2,2,-1,-1,1,-2, -1,0,0,0,-1,2,1,1],
   why:{
        0:"PVN 5% pirmās nepieciešamības pārtikai; PVN 12% ēdināšanas nozarei",
        1:"NĪN 0% primārajam mājoklim",
        3:"atbalsts nacionālas nozīmes infrastruktūras objektiem (ostas, lidostas, lielceļi, tilti u. c.)",
        4:"stabila pensiju sistēma; pabalstu pielāgošana inflācijai; bāzes pensijas nodrošināšana; vidējā pensija 1000 €",
        5:"bērna piedzimšanas pabalsts 2000 €; pabalsti un nodokļu/atlaižu programmas ģimeņu drošībai",
        6:"veselībai – 6% no IKP; ikgadējs nozares budžeta pieaugums līdz 6% no IKP",
        7:"pašvaldību finanšu ilgtspējas nodrošināšana; lielāka pašvaldību rīcības brīvība",
        10:"nelokāms atbalsts Ukrainai un Latvijas uzņēmēju iesaiste tās atjaunošanā",
        11:"aizsardzības industrija (munīcija, droni, enerģētika) – drošības finansējums paliek Latvijas ekonomikā",
        12:"stiprināta dalība ES un NATO; aktīva iesaiste starptautisko organizāciju un partnerību darbībā",
        13:"gudra imigrācijas politika – nepieļaut nelegālu imigrāciju; priekšroka augsti kvalificētam darbaspēkam terminētam darbam",
        14:"NBS, Zemessardzes un iekšlietu sistēmas spēju stiprināšana",
        15:"stiprināta dalība ES un NATO, nelokāms atbalsts Ukrainai",
        16:"mazāk nepārtrauktu un vairāk pabeigtu, izvērtētu reformu",
        20:"ministriju skaita samazināšana un funkciju deleģēšana; valsts izdevumu un funkciju audits, ietaupot vismaz 500 milj. €",
        21:"2% no IKP augstākajai izglītībai un zinātnei; augstskolu un pētniecības iesaistes padziļināšana inovāciju ekosistēmā",
        22:"2% no IKP augstākajai izglītībai un zinātnei; augstskolu attīstība reģionu vajadzībām",
        23:"izglītība visos līmeņos – iekļaujoša, stabila, kvalitatīva, ar izcilību un laukos pieejama"
   },
   points:["Veselībai 6 %, zinātnei 2 %, aizsardzībai virs 5 % no IKP","Minimālā alga 1250, vidējā alga 2500, vidējā pensija 1000 eiro līdz 2030. gadam","Piedzimšanas pabalsts 2000 eiro; brīvpusdienas līdz 9. klasei","PVN 5 % pārtikai, 12 % ēdināšanai; NĪN 0 % primārajam mājoklim","Valsts izdevumu audits ar 500 milj. eiro ietaupījumu veselībai un reģioniem"]},

  {nr:5, name:"Nacionālā apvienība",
   pos:[0,0,0,0,0,-2,1,0, 2,-2,2,2,0,2,2,-2, 0,0,0,0,-1,1,1,2],
   why:{
        5:"Palielināsim bērna kopšanas pabalstu līdz 600 EUR ar ikgadēju indeksāciju",
        6:"Samazināsim rindas pie speciālistiem, konsolidējot publisko un privāto finansējumu efekīvākai veselības aprūpei",
        8:"Paplašināsim atbalstu pilsoņiem, kuri dien NBS, ZS un VAD – finansiāli un karjeras garantijās",
        9:"Pārrausim ekonomiskās saites ar Krieviju un Baltkrieviju",
        10:"Atbalstīsim Ukrainu militāri, politiski un ekonomiski līdz uzvarai; iestāsimies par tās uzņemšanu ES un NATO",
        11:"Aizsardzības finansējumu palielināsim virs 5% no IKP, attīstot vietējo militāro industriju",
        13:"Stingra imigrācijas politika; Veicināsim Latvijai nelojālu personu un Krievijas pilsoņu izceļošanu no valsts",
        14:"Celsim iekšlietu dienestu kapacitāti un atalgojumu, vienlaikus modernizējot procesus un mazinot birokrātiju",
        15:"Atbalstīsim Ukrainu militāri, politiski un ekonomiski līdz uzvarai",
        20:"Ieviesīsim MI risinājumus valsts pārvaldē, samazinot administratīvo slogu; Pārskatīsim funkciju dublēšanos starp ministrijām un pašvaldībām",
        21:"Veicināsim zinātnes, inovāciju un uzņēmējdarbības ciešu un saskaņotu sadarbību",
        22:"Dzēsīsim studiju kredītus: 50% par pirmo bērnu, 90% par otro",
        23:"Atbalstīsim lauku kopienu pakalpojumu saglabāšanu: pasta punkti, ģimenes ārsti, mazās skolas, bibliotēkas"
   },
   points:["Aizsardzība virs 5 % no IKP, vietējā militārā industrija","Iekšlietu dienestu kapacitāte un algas, patvertnes, stratēģiskās rezerves","Bērna kopšanas pabalsts līdz 600 eiro","Lielāki ģimenes valsts pabalsti","15 000 eiro grants hipotekārā kredīta dzēšanai par katru bērnu"]},

  {nr:6, name:"Gobzema saraksts",
   pos:[-2,2,0,0,1,-2,0,0, 0,1,-1,2,1,2,2,1, 2,0,-2,-2,-2,0,0,2],
   why:{
        0:"Pārtikas produktiem noteiksim PVN likmi 12 procentu apmērā; Atceļot iedzīvotāju ienākuma nodokli daudzbērnu ģimenēm",
        1:"Mēs pilnībā atcelsim nekustamā īpašuma nodokli mājsaimniecībām par to vienīgo mājokli",
        4:"Nodrošināsim bezmaksas sabiedrisko transportu pensionāriem visā Latvijas teritorijā, sniedzot pilnīgu mobilitāti",
        5:"Valsts garantēs vismaz 5000 eiro vienreizēju pabalstu par katra bērna piedzimšanu",
        9:"Krievijas un Ukrainas konfliktā Latvija neieņems aktīvu, priekšplānā ejošu pozīciju",
        10:"Krievijas un Ukrainas konfliktā Latvija neieņems aktīvu, priekšplānā ejošu pozīciju, kas nepamatoti palielina riskus mūsu pašu drošībai",
        11:"Latvijas galvenā militārā prioritāte būs pašmāju dronu ražošanas, pretgaisa aizsardzības un elektroniskās cīņas sistēmu tūlītēja un masveidīga ieviešana",
        12:"Mums ir kopēja Eiropas Savienības ārpolitika, kuras ietvaros mēs darbojamies kā pragmatiski partneri, aizstāvot savas nacionālās ekonomiskās intereses",
        13:"Mēs iestājamies par stingru un nacionālajās interesēs balstītu migrācijas politiku; kategoriski iebilstam pret masveida migrāciju",
        14:"mēs dubultosim algas policistiem, ugunsdzēsējiem un robežsargiem",
        15:"Krievijas un Ukrainas konfliktā Latvija neieņems aktīvu, priekšplānā ejošu pozīciju",
        16:"valsts politikas centrā mēs izvirzām tradicionālo ģimeni, radikālu atbalstu dzimstībai un izglītības sistēmas pilnīgu pārveidi",
        18:"Mājasdarbu sistēma tiks pilnībā atcelta, lai viss mācību process un vielas apguve paveiktos skolā",
        19:"Mēs panāksim Satversmes grozījumus, lai Latvijas Valsts prezidentu turpmāk vēlētu visa tauta; Samazināsim referenduma ierosināšanai nepieciešamo slieksni līdz 50 000 parakstu",
        20:"Mūsu solījums vēlētājam ir mazāks valsts aparāts, vairāk brīvības cilvēkam",
        23:"Pirmsskolas izglītības iestādēm un sākumskolām ir jābūt maksimāli tuvu bērna dzīvesvietai"
   },
   points:["Ģimenes ar 3 un vairāk bērniem bez IIN; 5000 eiro par katra bērna piedzimšanu","1000 eiro mēnesī par bērnu līdz 2 gadiem","Atcelt mājasdarbus; bezmaksas ēdināšana no bērnudārza līdz 12. klasei","NĪN atcelšana vienīgajam mājoklim, bezmaksas transports pensionāriem, brīvprātīgs pensiju 2. līmenis","Reālpolitika Krievijas–Ukrainas karā; prioritāte dronu ražošanai un pretgaisa aizsardzībai"]},

  {nr:7, name:"Apvienotais saraksts",
   pos:[1,0,2,-1,0,-1,1,2, 2,-2,2,2,-1,0,1,-2, -2,0,1,0,0,1,1,0],
   why:{
        0:"Stabilizēsim nodokļu politiku. Pārtrauksim nodokļu regulāru pārskatīšanu, kas traucē ilgtermiņa investīciju piesaistei",
        2:"Mūsu prioritāte ir ieviest kārtību valsts finansēs, lai sasniegtu bezdeficīta bāzes budžetu četru gadu laikā",
        3:"Pārskatīsim “Rail Baltica” apjomu uz minimālo realizējamo, ieviesīsim pilnu finanšu caurredzamību un izmaksu kontroli",
        5:"Nodrošināsim iespēju strādāt bērna kopšanas laikā, nezaudējot bērna kopšanas pabalstu",
        6:"Publiskās investīcijas novirzīsim tur, kur tās rada ilgtermiņa vērtību: drošībai, enerģētikai, veselībai, izglītībai, mājokļiem, reģionālajai attīstībai",
        7:"Izveidosim valsts garantiju programmu mājokļu būvniecībai reģionos, lai palielinātu kreditēšanu par 2 miljardiem",
        8:"Paplašināsim Valsts aizsardzības dienestu, piedāvājot papildu dienesta virzienus, kas nepieciešami visaptverošai valsts aizsardzībai",
        9:"noturību pret Krievijas agresiju un hibrīduzbrukumiem",
        10:"Turpināsim nelokāmu atbalstu Ukrainai, vienlaikus stiprinot Latvijas aizsardzības industriju, militāro mobilitāti un noturību pret Krievijas agresiju un hibrīduzbrukumiem",
        11:"Attīstīsim dronu un pretdronu spējas, iesaistot vietējos ražotājus un paņemot labāko no Ukrainas pieredzes",
        12:"Iestājamies par stipru Latviju stiprā NATO un ES, ciešā sadarbībā ar ASV, Apvienoto Karalisti, Ziemeļvalstīm, Baltijas valstīm un demokrātiskajiem sabiedrotajiem",
        14:"Stiprināsim policiju, robežsardzi un VUGD, tostarp ar apdraudējumiem atbilstošu materiāltehnisko un tehnoloģisko nodrošinājumu",
        15:"Iestājamies par stipru Latviju stiprā NATO un ES",
        16:"Pilnveidosim “Skola2030”, sadarbojoties ar pedagogiem, vecākiem un skolām",
        18:"Sakārtosim vērtēšanas sistēmu, organizēsim samērīgu eksāmenu norisi",
        21:"Nodrošināsim profesionālās ievirzes skolu bāzes finansējumu, augstskolu inovāciju klāsterus drošības un ekonomikas jomās",
        22:"Novados piesaistīsim mediķus ar mērķstipendijām, mājokļu atbalstu un prakšu programmām"
   },
   points:["Bezdeficīta bāzes budžets četru gadu laikā","Latvijas Attīstības fonds","10 % mikrouzņēmumu nodoklis fiziskām personām, mazāks kapitāla pieauguma nodoklis","2 miljardu eiro kreditēšanas pieaugums reģionu mājokļiem","Paplašināt VAD; PPP projekti aizsardzībā, enerģētikā un infrastruktūrā"]},

  {nr:8, name:"Latvija pirmajā vietā",
   pos:[-2,2,0,1,1,-2,0,2, 0,0,1,0,2,1,1,-1, 0,0,-1,-2,-2,0,0,2],
   why:{
        0:"Darbaspēka nodokļus samazināsim vismaz līdz Eiropas vidējam līmenim",
        1:"Atcelsim nekustamā īpašuma nodokli vienīgajam mājoklim",
        3:"Īstenosim ne mazāk kā 10 infrastruktūras projektus, kuru kopējā vērtība sasniedz vismaz 10 miljardus eiro",
        4:"Veicinot ekonomiku, celsim vidējo atalgojumu valstī un pensijas",
        5:"Ieviesīsim 5000 eiro pabalstu par katru jaundzimušo bērnu",
        7:"Lai veicinātu reģionu attīstību, pusi no UIN atdosim pašvaldībām",
        10:"Atbalstīsim Ukrainas iestāšanos ES",
        12:"Nostiprināsim Latvijas suverenitāti un nodrošināsim, ka valsts pati nosaka savu nākotni un pieņem lēmumus savu iedzīvotāju interesēs",
        13:"Uzsāksim bezprecedenta cīņu ar nelegālo migrāciju, lai Latvijas robežas būtu drošas",
        14:"Apvienosim Iekšlietu un Aizsardzības ministrijas, lai garantētu valsts drošību un ieviestu vienotu atalgojuma sistēmu militārpersonām, policistiem, ugunsdzēsējiem un glābējiem",
        15:"Kopā ar Eiropas Savienību un NATO partnervalstīm rūpēsimies par mieru un stabilitāti Eiropā",
        18:"Ieviesīsim vienkāršotu vērtēšanas sistēmu ar mērķi nesodīt skolēnus",
        19:"Veiksim izmaiņas Satversmē, ļaujot Valsts prezidentu ievēlēt Latvijas tautai",
        20:"Lai samazinātu birokrātiju un izdevumus valsts pārvaldē, apvienosim valsts iestādes un ministrijas",
        23:"Atbalstīsim lauku un reģionu skolu saglabāšanu, vērtējot to pastāvēšanu ne tikai pēc skolēnu skaita, bet arī pēc pieejamības, izglītības kvalitātes un nozīmes vietējai kopienai"
   },
   points:["10 % UIN un 10 % kapitāla pieauguma nodoklis","PVN 10 % plašam preču un pakalpojumu lokam","NĪN atcelšana vienīgajam mājoklim; puse UIN pašvaldībām","10 PPP projekti par 10 miljardiem eiro, koncertzāle, stadions, Laikmetīgās mākslas muzejs","5000 eiro pabalsts par katru jaundzimušo"]},

  {nr:9, name:"Jaunā Vienotība",
   pos:[-1,-2,1,2,0,0,2,1, 0,-2,2,2,-2,2,1,-2, 0,0,0,0,0,2,1,0],
   why:{
        0:"palielināsim fiksēto neapliekamo minimumu līdz 80% no minimālās algas, mazinot darbaspēka nodokļu slogu zemāko ienākumu saņēmējiem",
        1:"Padarīsim nekustamā īpašuma nodokli par pilnvērtīgu pašvaldību nodokli ar prognozējamību un sociālo taisnīgumu",
        2:"Veidosim fiskāli atbildīgu budžetu ar valsts ārējā parāda līmeni zem 55% no IKP, ievērojot eirozonas fiskālos noteikumus",
        3:"Satiksmē nodrošināsim «Rail Baltica», reģionālo ceļu, dzelzceļa, ostu, sabiedriskā transporta un digitālās infrastruktūras attīstību",
        6:"Veidosim prognozējamu veselības finansējumu ne mazāk kā 6% no IKP",
        7:"Veidosim taisnīgu un uzņēmējdarbību veicinošu nodokļu ieņēmumu sadali starp pašvaldībām un valsti",
        9:"Uzturēsim starptautisko spiedienu pret Krieviju, stiprināsim sankcijas un pārtrauksim ekonomisko ietekmējamību no Krievijas un Baltkrievijas",
        10:"Turpināsim visaptverošu politisku, militāru un diplomātisku atbalstu Ukrainai līdz taisnīgam mieram",
        11:"Attīstīsim vietējo militāro un divējāda lietojuma industriju, lai ieguldījumi vienlaikus stiprinātu arī Latvijas ražošanu, zinātni un eksportu",
        12:"Stipra valsts sargā savus cilvēkus, runā skaidrā latviešu valodā, ir Eiropas un NATO kodolā",
        13:"noteiksim stingrākus nosacījumus trešo valstu pilsoņu uzturēšanās, studiju un nodarbinātības jomā",
        14:"Stiprināsim civilās aizsardzības sistēmu un iekšlietu dienestu – ugunsdzēsēju, policijas, robežsardzes kapacitāti",
        15:"Nodrošināsim aizsardzības finansējumu 5% no IKP un attīstīsim NATO sabiedroto pastāvīgu klātbūtni Latvijā",
        21:"Virzīsimies uz ieguldījumiem pētniecībā un attīstībā 3% no IKP, stiprinot valsts pētījumu programmas, bāzes finansējumu",
        22:"Veidosim elastīgu, darba vidē balstītu profesionālo izglītību un augstskolas kā reģionālus un nacionālus zināšanu un inovāciju centrus"
   },
   points:["Veselības finansējums vismaz 6 % no IKP","Pētniecībai un attīstībai 3 % no IKP","Aizsardzībai 5 % no IKP, NATO sabiedroto klātbūtne","Investīcijas virs 30 % no IKP, vismaz 3,5 % izaugsme gadā","Latvija ES un NATO kodolā; sankcijas pret Krieviju, atbalsts Ukrainai"]},

  {nr:10, name:"Jaunā konservatīvā partija",
   pos:[1,2,0,2,0,-1,2,2, 2,0,2,2,0,2,1,-2, 0,-1,0,0,-2,1,1,0],
   why:{
        0:"Veidosim STABILU UN KONKURĒTSPĒJĪGU NODOKĻU POLITIKU investīciju, ekonomikas izaugsmes un reģionu attīstībai, nepieļaujot HAOTISKAS NODOKĻU IZMAIŅAS",
        1:"Rosināsim NEKUSTAMĀ ĪPAŠUMA NODOKĻA ATCELŠANU MĀJOKĻIEM",
        3:"Attīstīsim STRATĒĢISKUS ĀTRGAITAS AUTOCEĻU KORIDORUS uz Liepāju, Ventspili, Daugavpili, Alūksni, Lietuvu un Igauniju",
        5:"Veidosim ĢIMENĒM DRAUDZĪGU UN DZIMSTĪBU VEICINOŠU POLITIKU, mazinot ekonomiskos šķēršļus bērnu audzināšanai",
        6:"Veicināsim VALSTS FINANSĒJUMA VESELĪBAS APRŪPEI apjoma tuvināšanu Eiropas attīstīto valstu vidējam līmenim",
        7:"Daļu UIN un PVN novirzīsim uzņēmuma darbības vietas pašvaldībai, radot pašvaldībām tiešu ieinteresētību investīciju un uzņēmējdarbības piesaistē",
        8:"Pilnveidosim VALSTS AIZSARDZĪBAS DIENESTU UN ZEMESSARDZI, pielāgojot to mūsdienu karadarbības prasībām",
        10:"Veidosim MILITĀRI TEHNOLOĢISKU ALIANSI AR UKRAINU, pārņemot kara pieredzi un attīstot kopīgus aizsardzības industrijas projektus",
        11:"Attīstīsim LATVIJAS MILITĀRO INDUSTRIJU kā valsts drošības un ekonomiskās izaugsmes balstu, pilnveidojot iepirkumus un veicinot vietējo ražotāju iesaisti NBS apgādē",
        13:"Iestāsimies par STINGRU UN KONTROLĒTU IMIGRĀCIJAS POLITIKU, nosakot augstas integrācijas prasības un prioritāti Latvijas ilgtermiņa interesēm",
        14:"Iestāsimies par POLICIJAS PASTĀVĪGU KLĀTBŪTNI REĢIONOS, izveidojot reģionālos drošības centrus ar skaidru teritoriālo atbildību",
        15:"Stiprināsim sadarbību ar NATO, ZIEMEĻVALSTĪM, Kanādu un ASV, panākot lielāku sabiedroto klātbūtni",
        17:"Stiprināsim LATVIEŠU VALODAS LOMU izglītībā, publiskajā telpā un valsts pārvaldē",
        20:"Veidosim EFEKTĪVU, profesionālu un uz rezultātu orientētu VALSTS PĀRVALDI, mazinot birokrātiju, izvērtējot valsts iestāžu funkcijas, apvienošanas iespējas un nepieciešamās strukturālās reformas",
        21:"Atbalstīsim ILGTSPĒJĪGU PĒCDOKTORANTŪRAS FINANSĒJUMU un jauno zinātnieku izaugsmi, mazinot talantīgu PĒTNIEKU aizplūšanu no Latvijas",
        22:"Veicināsim JAUNO SPECIĀLISTU PIESAISTI REĢIONIEM ar mājokļa un studiju atbalsta programmām"
   },
   points:["Daļu UIN un PVN pašvaldībai, kurā darbojas uzņēmums","Rosināt NĪN atcelšanu mājokļiem","Reģionu kreditēšana un jaunie speciālisti reģioniem","Ātrgaitas autoceļu koridori","Latvija kā Baltijas militārās industrijas centrs"]},

  {nr:11, name:"Latvijas attīstībai",
   pos:[0,0,2,2,0,0,1,2, 1,0,2,2,-2,0,0,-2, 0,0,0,0,-1,2,1,0],
   why:{
        2:"Mūsu mērķis ir līdz 2030. gadam panākt sabalansētu valsts budžetu, vienlaikus saglabājot spēju ieguldīt drošībā, izglītībā, veselības aprūpē",
        3:"Turpināsim attīstīt transporta infrastruktūru, ostas, lidostu, dzelzceļu un digitālos sakarus, lai Latvija kļūtu par modernu Ziemeļeiropas loģistikas, inovāciju un uzņēmējdarbības centru",
        6:"Veselības aprūpes centrā jābūt cilvēkam",
        7:"Attīstīsim reģionu ekonomiku, transporta un digitālo infrastruktūru, stiprināsim pašvaldību kapacitāti un veicināsim investīciju piesaisti ārpus Rīgas",
        8:"Attīstīsim Nacionālos bruņotos spēkus, Zemessardzi, civilo aizsardzību un kiberdrošību",
        10:"Turpināsim visaptverošu politisko, militāro un humāno atbalstu Ukrainai līdz taisnīga un ilgtspējīga miera panākšanai",
        11:"saglabāsim aizsardzības finansējumu vismaz 5 % apmērā no iekšzemes kopprodukta, vienlaikus mērķtiecīgi attīstot Latvijas aizsardzības industriju",
        12:"Latvijas drošība balstās spēcīgā NATO, vienotā Eiropas Savienībā un ciešā sadarbībā ar Baltijas un Ziemeļvalstīm",
        15:"Latvijas drošība balstās spēcīgā NATO, vienotā Eiropas Savienībā",
        20:"Samazināsim birokrātiju, uzlabosim regulējuma kvalitāti un attīstīsim kapitāla tirgu",
        21:"Latvijai jākļūst par valsti, kur zinātne, augstākā izglītība un uzņēmējdarbība darbojas vienotā inovāciju ekosistēmā",
        22:"Skolotāja profesijai jākļūst par vienu no pievilcīgākajām sabiedrībā"
   },
   points:["Aizsardzībai vismaz 5 % no IKP","Pētniecībai un attīstībai vismaz 2 % no IKP","Pedagogu algas vismaz 1,2 vidējās algas līmenī","Sabalansēts budžets līdz 2030. gadam","Latvija kā Eiropas aizsardzības industrijas partneris"]},

  {nr:12, name:"Austošā Saule Latvijai",
   pos:[-1,2,0,2,1,-2,1,2, 1,-2,2,2,1,2,2,-2, 0,-2,0,0,-2,2,2,2],
   why:{
        0:"Palielināsim IIN neapliekamo minimumu vidējās algas apmērā – šobrīd 1900 eiro mēnesī",
        1:"Atcelsim NĪN vienīgajam ģimenes mājoklim",
        3:"Atjaunosim autoceļu fondu ar speciālo budžetu un 80 % no akcīzes nodokļa par naftas produktiem",
        4:"Nodrošināsim pensiju taisnīgumu māmiņām",
        5:"Veicināsim latviešu tautas ataudzi, lai sasniegtu summāro dzimstības koeficientu vismaz 2,1 apmērā",
        6:"Bērnu veselība kā prioritāte – ambulatorie pediatri pieejami novadu centros",
        7:"Finansēšanas mehānismā iestrādāsim uzņēmējdarbības piesaistes kritēriju, atbalstu lauku skolām un reģionālajai mobilitātei",
        8:"Celsim Nacionālo bruņoto spēku (NBS) spējas, nodrošinot gatavību 30 dienas patstāvīgi aizsargāt austrumu robežu",
        9:"Pilnīga sadarbības un tirdzniecības pārtraukšana ar Krieviju, Baltkrieviju un citām terorismu atbalstošām valstīm",
        10:"Atbalstīsim Ukrainas ceļu uz NATO",
        11:"Attīstīsim dronu un pretdronu sistēmas, pārņemot Ukrainas pieredzi",
        12:"Eiropas Savienība kā vienā civilizācijā balstīta nacionālu valstu kopiena",
        13:"Masu imigrācijas apturēšana",
        14:"Palielināsim policijas darbinieku vidējo atalgojumu par 30–50 % piecu gadu laikā",
        15:"Stiprināsim divpusējo sadarbību ar ASV, īpaši NATO ietvaros",
        17:"Būtiski stiprināsim latviešu valodu un aizsargāsim tās lietotājus, nosakot atbildību par necieņu pret to un nepamatotu krievu valodas prasību uzspiešanu darba tirgū",
        20:"Samazināsim valsts pārvaldes aparātu un birokrātiju – iesaldēsim administratīvo līdzekļu daļu valsts pārvaldē, apvienosim un likvidēsim liekās ministrijas",
        21:"Radīsim modernu ekosistēmu zinātnes komercializācijai un efektīviem iepirkumiem",
        22:"akadēmisko un sociālo studentu stipendiju paaugstināšana līdz pārējo Baltijas valstu līmenim",
        23:"Stiprināsim lauku skolu tīklu"
   },
   points:["Neapliekamais minimums vidējās algas apmērā","NĪN atcelšana vienīgajam ģimenes mājoklim","Piedzimšanas pabalsts trīs vidējo algu apmērā","Par katru bērnu mātei 20 000 eiro pensijas 1. līmeņa kapitālā","Pilnīga tirdzniecības pārtraukšana ar Krieviju un Baltkrieviju; Ukrainas ceļš uz NATO"]},

  {nr:13, name:"Stabilitātei!",
   pos:[-2,2,2,-1,1,-2,2,1, -2,2,-2,0,2,0,0,2, 2,2,0,-2,-2,0,0,0],
   why:{
        0:"Samazināt PVN līdz 12% pamatpārtikas produktiem",
        1:"Atcelt nekustamā īpašuma nodokli vienīgajam mājoklim",
        2:"Veidot bezdeficīta valsts budžetu",
        3:"Veidot valsts budžetu bez kredītu un aizņēmumu piesaistes",
        4:"Stiprināt sociālo aizsardzību",
        5:"Palielināt atbalstu jaunajām ģimenēm un daudzbērnu vecākiem",
        6:"Palielināt veselības aprūpes finansējumu",
        7:"Uzlabot medicīnas pieejamību reģionos",
        8:"Atteikties no obligātā valsts aizsardzības dienesta",
        9:"Atjaunot ekonomisko sadarbību ar Krieviju un Baltkrieviju visās nozarēs, kur tas atbilst Latvijas Republikas interesēm",
        10:"Izvairīties no iesaistīšanās citu valstu militāros konfliktos",
        12:"Šī programma piedāvā skaidru alternatīvu: stiprāku ekonomiku, taisnīgāku valsts pārvaldi, sociālo drošību un reālu neatkarību lēmumu pieņemšanā",
        15:"Valsts neitralitātes atjaunošana un atteikšanās no dalības militāros konfliktos starp citām valstīm",
        16:"Atteikties no programmas „Skola 2030”",
        17:"Nodrošināt iespēju iegūt izglītību dzimtajā valodā (krievu valodā, lietuviešu valodā, angļu valodā, poļu valodā u.c.)",
        19:"Nodrošināt, ka Latvijas Valsts prezidentu tiešās vēlēšanās ievēl Latvijas pilsoņi",
        20:"Samazināt ierēdņu skaitu"
   },
   points:["Budžets bez deficīta un aizņēmumiem; valsts pārvalde mazāka par 30 %","Neitralitāte, atteikšanās no obligātā VAD, ekonomiskā sadarbība ar Krieviju un Baltkrieviju, sankciju pārskatīšana","PVN pamatpārtikai 12 %, recepšu zālēm 5 %; bez NĪN vienīgajam mājoklim","Tautas vēlēts prezidents, Saeimā 50 deputāti, nepilsoņa statusa likvidēšana","Atteikties no “Skola 2030”; izglītība dzimtajā valodā"]},

  {nr:14, name:"Progresīvie",
   pos:[-2,0,0,0,2,-2,2,2, 0,0,1,2,-2,-1,0,-2, 0,0,-1,0,0,2,2,1],
   why:{
        0:"Ieviesīsim plašāku progresivitāti, koriģējot ienākumu sliekšņus un likmes, lai samazinātu nodokļus mazajām un vidējām algām",
        4:"Paaugstināsim pensijas, straujāk ieviešot piemaksu par apdrošināšanas stāžu un atzīstot dažādu nodarbinātības formu ietvarā paveikto",
        5:"Palielināsim ģimenes valsts pabalstu un vienkāršosim pieteikšanos atbalstam pēc bērna piedzimšanas",
        6:"Valstij vairāk jāinvestē sabiedriskajos pakalpojumos – veselības aprūpē, izglītībā, mājokļu būvniecībā",
        7:"Veidosim taisnīgu un stabilu pašvaldību finanšu izlīdzināšanas modeli",
        10:"Latvijai jābūt aktīvai NATO austrumu flanga valstij, kas reaģē, paredz un novērš draudus sadarbībā ar NATO, ES, NB8+, Poliju, Lielbritāniju un Ukrainu",
        11:"Veidosim aizsardzības industrijas parkus ar sakārtotu infrastruktūru, ātrākiem lēmumiem un atbalstu inovācijām un ražošanai atbilstoši NBS vajadzībām",
        12:"Progresīvie stingri iestāsies par Latvijas ciešāku integrāciju Eiropas Savienībā",
        13:"Veidosim gudru, tālredzīgu un drošu migrācijas politiku ar mērķi nodrošināt cieņpilnus dzīves apstākļus Latvijas un Eiropas iedzīvotājiem",
        15:"Latvijai jābūt aktīvai NATO austrumu flanga valstij, kas reaģē, paredz un novērš draudus",
        18:"Līdzsvarosim skolēnu mācību slodzi pa vecumposmiem un atstāsim tikai jēgpilnus mājasdarbus",
        21:"Palielināsim „Studētgods” stipendijas, finansējumu zinātnei un augstākajai izglītībai",
        22:"Palielināsim „Studētgods” stipendijas, finansējumu zinātnei un augstākajai izglītībai",
        23:"Ieviesīsim programmu atbalsta personāla piesaistei reģionos"
   },
   points:["Lielāki ģimenes pabalsti, piesaistīti ienākumu mediānai","Pensiju paaugstināšana","Vienota sabiedriskā transporta mēnešbiļete","Gada līdzmaksājumu griesti kompensējamām zālēm","Plašāks mājokļu atbalsts; aizsardzībai vismaz 5 % no IKP"]}
];

const USER_LABEL = {2:"Pilnīgi piekrītu",1:"Drīzāk piekrītu",0:"Neitrāli",[-1]:"Drīzāk nepiekrītu",[-2]:"Pilnīgi nepiekrītu"};
const PARTY_LABEL = {2:"Piekrīt",1:"Drīzāk piekrīt",0:"Nav skaidras pozīcijas",[-1]:"Drīzāk nepiekrīt",[-2]:"Nepiekrīt"};
const MATCH = [{max:0,cls:"m0",txt:"Sakrīt"},{max:1,cls:"m1",txt:"Tuvu"},{max:2,cls:"m2",txt:"Daļēji"},{max:4,cls:"m3",txt:"Atšķiras"}];
const MIN_RANK = 3;   /* mazāk salīdzinājumu – bez procentiem */
const LOW_CONF = 6;   /* mazāk salīdzinājumu – “mazāk ticams” */
const MIN_EARLY = 12; /* pēc cik atbildēm var skatīt rezultātu */

window.PP = {DIMS, DIMS_SHORT, QUESTIONS, PARTIES, USER_LABEL, PARTY_LABEL, MATCH, MIN_RANK, LOW_CONF, MIN_EARLY};
})();
